config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      get 'logout' # Define custom action route for a specific member
    end
  end
  devise_for :users
  root 'posts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  def display_image
    # TODO: set host in evn file
    ActiveStorage::Current.set(url_options: { host: "http://localhost:3000" }) do 
      self.image&.url
    end
  end

  def sentiment_analysis
    Rails.cache.fetch("sentiment_analysis:#{id}") do
      SentimentAnalysis.new(content).analyze
    end
  end

  def sentiment_in_text
    sentiments = {
      "P+" => "strong positive",
      "P"  => "positive",
      "Neu"=> "neutral",
      "N"  => "negative",
      "N+" => "strong negative",
      "NONE" => "without polarity"
    }

    sentiments.fetch(sentiment_analysis, "no sentiment detected")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show, :logout]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @posts = @posts.where(created_at: params[:start_date]..params[:end_date]) if params[:start_date].present? && params[:end_date].present?
    respond_to do |format|
      format.html # Render HTML normally
      format.turbo_stream # Render Turbo Stream for partial updates
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def logout
    if current_user.present?
      sign_out(current_user)
    end
    redirect_to new_user_session_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :image)
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<!-- _navbar.html.erb -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">SkyPrep Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Posts", root_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Out', logout_posts_url, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkyprepBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="container">
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |attribute, error| %>
          <li><%= "#{attribute.to_s.humanize} #{error}" %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div><br/>

  <div class="form-group">
    <%= form.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="<%= post.display_image %>" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= post.content %></p>
      <p class="card-text">Sentiment Analysis: <%= post.sentiment_in_text %></p>
      <p><%= link_to "Show post", post %></p>
      <p class="card-text" style="text-align: right"><%= post.created_at.strftime('%m/%d/%Y') %></p>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>
<div style="text-align: right;">
  <%= link_to "New post", new_post_path, class: "btn btn-primary" %>
</div>

<div class="row">
  <%= form_with(url: posts_path, method: :get, class: "filter-form", "data-controller": "filter") do |form| %>
    <div class="col-md-3">
      <%= form.label :start_date, "Start Date" %>
      <%= form.date_field :start_date, id: "startDate", class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= form.label :end_date, "End Date" %>
      <%= form.date_field :end_date, id: "endDate", class: "form-control" %>
    </div>
    <br/>
    <div class="col">
      <%= form.submit "Filter", class: "btn btn-primary" %>
      <%= form.submit "clear", class: "btn btn-info" %>
    </div>
  <% end %>
</div>

<div id="posts" class="row">
  <% @posts.each do |post| %>
  <div class="col" style="padding-top: 30px" data-url="<%= post_path(post) %>">
    <%= render post %>
  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>